FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN echo "precedence ::ffff:0:0/96 100" >> /etc/gai.conf

COPY src ./src
COPY main.py .
COPY pyproject.toml .
COPY .env .

ENV PYTHONPATH=/app/src

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]